### ISSUE TITLE
iso_mapping empty

### ISSUE THREAD

**Issue by willu47** [openENTRANCE/openentrance#202]
The dictionary containing region mappings is empty in `openentrance v0.3.dev74+gbe22752` when I use a non-editable install.
```bash
$ pip install git+https://github.com/openENTRANCE/openentrance.git@main#egg=openentrance
$ pip list
openentrance                  0.3.dev74+gbe22752
$ python -c 'from openentrance import iso_mapping; print(iso_mapping)'
{}
```
Because it is not possible to denote a dependency as required to be installed as editable under a Python package (e.g. in the `install_requires` section), this means I cannot distribute my package without requiring a manual editable install of the openentrance package.

**Comment by willu47** [comment]
On further investigation, I found a hacky solution - you must use an editable install, so the following solves the issue:

`$ pip install git+https://github.com/openENTRANCE/openentrance.git@main#egg=openentrance`

To solve this so that the data structure is `installed` using pip, the data component of the openentrance package needs to be contained in the source code directory.

The [pyscaffold docs](https://pyscaffold.org/en/stable/features.html#package-and-files-data) has a good description of this

**Comment by willu47** [comment]
Yes, but note the above:

> Because it is not possible to denote a dependency as required to be installed as editable under a Python package (e.g. in the `install_requires` section of `setup.cfg`), this means I cannot distribute my package without requiring a manual editable install of the openentrance package.

**Comment by danielhuppmann** [comment]
Ok, now I got it why it's a problem...

How much of a headache is this for you? Or is there some timeline or release date by which you would be really happy if we came up with a better solution?

**Comment by willu47** [comment]
It's a bit of a pain, but given that it only really causes our small team of 3 people a headache, probably not a priority for now. We can manage with the manual editable install until a fix comes along (or I submit a PR).

**Comment by danielhuppmann** [comment]
Against stumbled over this issue. I think that the newly added countries-module in the **nomenclature** package serves the needs better than the openentrance utility.

See https://nomenclature-iamc.readthedocs.io/en/stable/api/countries.html for more info.
