### ISSUE TITLE
Secondary energy prices removed from the variables definition

### ISSUE THREAD

**Issue by Renato-Rodrigues** [openENTRANCE/openentrance#221]
Could I ask why secondary energy prices were removed from the variables definition files?

https://github.com/openENTRANCE/openentrance/commit/4730be9b4133f0f74e5c798e866f4e4477acd5aa#diff-9720cdd30a1b714d520da007c71b80ea771e9856553f248aaabd08d84f377adeL28

Ex: It can be quite important to know the price levels for fossil, biomass and/or synfuel based gases at secondary energy level. The same for liquids, solids and, specially, hydrogen. However, the above linked commit removed them from the db. 
The less than handful entries that remained in the database do not provide enough information to deeper analysis. 
Besides, the removed variables were already being in use for ECEMF analysis carried in WP1 and they are part of the variables template used by the modeling teams.

I would kindly request to the removed variables to be reinstated the database.

**Comment by danielhuppmann** [comment]
Thanks for raising this issue, there were some conflicts when we migrated to an updated version of the nomenclature package (with additional validation). I will reinsert the removed variables asap.
