### ISSUE TITLE
Rename of final energy non-energy use variable

### ISSUE THREAD

**Issue by Renato-Rodrigues** [openENTRANCE/openentrance#242]
https://github.com/openENTRANCE/openentrance/blob/e7ca29d3963fa5d63353406f1ee46e86c3d14be5/definitions/variable/energy/energy-final.yaml#L76

Was it intentional de rename of the `Final Energy|Non-Energy Use` to `Final Energy|Non-energy_use` in the commit https://github.com/openENTRANCE/openentrance/commit/becf3b1bbcdaa91b60dbef1174cf75b15510ec64 ?

**Comment by danielhuppmann** [comment]
Thank you for finding this typo, started a PR with the fix...
