### ISSUE TITLE
African regions within the openMod4Africa

### ISSUE THREAD

**Issue by erikfilias** [openENTRANCE/openentrance#305]
This issue will be used as a draft to define the African regions within the project openMod4Africa.

**Comment by erikfilias** [comment]
Country|Subregion: 

- Nigeria|Western Africa
- Ethiopia|Eastern Africa
- Egypt|Northern Africa
- DR Congo|Middle Africa
- Tanzania|Eastern Africa
- South Africa|Southern Africa
- Kenya|Eastern Africa
- Uganda|Eastern Africa
- Sudan|Northern Africa
- Algeria|Northern Africa
- Morocco|Northern Africa
- Angola|Middle Africa
- Ghana|Western Africa
- Mozambique|Eastern Africa
- Madagascar|Eastern Africa
- Côte d'Ivoire|Western Africa
- Cameroon|Middle Africa
- Niger|Western Africa
- Mali|Western Africa
- Burkina Faso|Western Africa
- Malawi|Eastern Africa
- Zambia|Eastern Africa
- Chad|Middle Africa
- Somalia|Eastern Africa
- Senegal|Western Africa
- Zimbabwe|Eastern Africa
- Guinea|Western Africa
- Rwanda|Eastern Africa
- Benin|Western Africa
- Burundi|Eastern Africa
- Tunisia|Northern Africa
- South Sudan|Eastern Africa
- Togo|Western Africa
- Sierra Leone|Western Africa
- Libya|Northern Africa
- Congo|Middle Africa
- Central African Republic|Middle Africa
- Liberia|Western Africa
- Mauritania|Western Africa
- Eritrea|Eastern Africa
- Gambia|Western Africa
- Botswana|Southern Africa
- Namibia|Southern Africa
- Gabon|Middle Africa
- Lesotho|Southern Africa
- Guinea-Bissau|Western Africa
- Equatorial Guinea|Middle Africa
- Mauritius|Eastern Africa
- Eswatini|Southern Africa
- Djibouti|Eastern Africa
- Comoros|Eastern Africa
- Cabo Verde|Western Africa
- Sao Tome & Principe|Middle Africa
- Seychelles|Eastern Africa

**Comment by danielhuppmann** [comment]
Thanks @erikfilias, cc @phackstock!

Two comments:
1. We are working on an easier way to add all countries to a Scenario Explorer database and also create a utility for mapping between country names and ISO2/ISO3 codes, see https://github.com/IAMconsortium/nomenclature/pull/263
2. It would be easier to read this list if you format it as a table or similar.

**Comment by erikfilias** [comment]
> Thanks @erikfilias, cc @phackstock!
> 
> Two comments:
> 
> 1. We are working on an easier way to add all countries to a Scenario Explorer database and also create a utility for mapping between country names and ISO2/ISO3 codes, see [Add a module for translating between country names and alpha-2/3 codes IAMconsortium/nomenclature#263](https://github.com/IAMconsortium/nomenclature/pull/263)
> 2. It would be easier to read this list if you format it as a table or similar.

Perfect!
A table in markdown format? 
If it is, please consider the next table: 
| Country                  | Subregion       |
| ------------------------ | --------------- |
| Nigeria                  | Western Africa  |
| Ethiopia                 | Eastern Africa  |
| Egypt                    | Northern Africa |
| DR Congo                 | Middle Africa   |
| Tanzania                 | Eastern Africa  |
| South Africa             | Southern Africa |
| Kenya                    | Eastern Africa  |
| Uganda                   | Eastern Africa  |
| Sudan                    | Northern Africa |
| Algeria                  | Northern Africa |
| Morocco                  | Northern Africa |
| Angola                   | Middle Africa   |
| Ghana                    | Western Africa  |
| Mozambique               | Eastern Africa  |
| Madagascar               | Eastern Africa  |
| Côte d'Ivoire            | Western Africa  |
| Cameroon                 | Middle Africa   |
| Niger                    | Western Africa  |
| Mali                     | Western Africa  |
| Burkina Faso             | Western Africa  |
| Malawi                   | Eastern Africa  |
| Zambia                   | Eastern Africa  |
| Chad                     | Middle Africa   |
| Somalia                  | Eastern Africa  |
| Senegal                  | Western Africa  |
| Zimbabwe                 | Eastern Africa  |
| Guinea                   | Western Africa  |
| Rwanda                   | Eastern Africa  |
| Benin                    | Western Africa  |
| Burundi                  | Eastern Africa  |
| Tunisia                  | Northern Africa |
| South Sudan              | Eastern Africa  |
| Togo                     | Western Africa  |
| Sierra Leone             | Western Africa  |
| Libya                    | Northern Africa |
| Congo                    | Middle Africa   |
| Central African Republic | Middle Africa   |
| Liberia                  | Western Africa  |
| Mauritania               | Western Africa  |
| Eritrea                  | Eastern Africa  |
| Gambia                   | Western Africa  |
| Botswana                 | Southern Africa |
| Namibia                  | Southern Africa |
| Gabon                    | Middle Africa   |
| Lesotho                  | Southern Africa |
| Guinea-Bissau            | Western Africa  |
| Equatorial Guinea        | Middle Africa   |
| Mauritius                | Eastern Africa  |
| Eswatini                 | Southern Africa |
| Djibouti                 | Eastern Africa  |
| Comoros                  | Eastern Africa  |
| Cabo Verde               | Western Africa  |
| Sao Tome & Principe      | Middle Africa   |
| Seychelles               | Eastern Africa  |

**Comment by MohElabbas** [comment]
Apologies for the late comment, but in my opinion, the classification of countries into subregions based on the UN Methodology M49 Standard does not make sense, especially in energy modelling. This standard - which classifies Sudan (my own country) to Northern Africa, Mozambique, Zambia and Zimbabwe to Eastern Africa, and calls Central Africa as Middle Africa - is bizarre to me, and I have never encountered it in energy modelling literature. I am afraid such an aggregation won't make sense to our African stakeholders. I suggest we use the African Union classification (the OAU, CM/Res.464QCXVI, of 1976). You can find it here https://au.int/en/member_states/countryprofiles2 
Here, I am adding it in a table format:

| Member State                                  |  Abbreviation             | Subregion       |
|-----------------------------------------------|---------------------------|-----------------|
| Republic of Burundi                           |  Burundi                  | Central Africa  |
| Republic of Cameroon                          |  Cameroon                 | Central Africa  |
| Central African Republic                      |  Central African Republic | Central Africa  |
| Republic of Chad                              |  Chad                     | Central Africa  |
| Republic of the Congo                         |  Congo Republic           | Central Africa  |
| Democratic Republic of Congo                  |  DR Congo                 | Central Africa  |
| Republic of Equatorial Guinea                 |  Equatorial Guinea        | Central Africa  |
| Gabonese Republic                             |  Gabon                    | Central Africa  |
| Democratic Republic of São Tomé and Príncipe  |  São Tomé and Príncipe    | Central Africa  |
| Union of the Comoros                          |  Comoros                  | Eastern Africa  |
| Republic of Djibouti                          |  Djibouti                 | Eastern Africa  |
| State of Eritrea                              |  Eritrea                  | Eastern Africa  |
| Federal Democratic Republic of Ethiopia       |  Ethiopia                 | Eastern Africa  |
| Republic of Kenya                             |  Kenya                    | Eastern Africa  |
| Republic of Madagascar                        |  Madagascar               | Eastern Africa  |
| Republic of Mauritius                         |  Mauritius                | Eastern Africa  |
| Republic of Rwanda                            |  Rwanda                   | Eastern Africa  |
| Republic of Seychelles                        |  Seychelles               | Eastern Africa  |
| Federal Republic of Somalia                   |  Somalia                  | Eastern Africa  |
| Republic of South Sudan                       |  South Sudan              | Eastern Africa  |
| Republic of the Sudan                         |  Sudan                    | Eastern Africa  |
| United Republic of Tanzania                   |  Tanzania                 | Eastern Africa  |
| Republic of Uganda                            |  Uganda                   | Eastern Africa  |
| People’s Democratic Republic of Algeria       | Algeria                   | Northern Africa |
| Arab Republic of Egypt                        | Egypt                     | Northern Africa |
| Libya                                         | Libya                     | Northern Africa |
| Islamic Republic of Mauritania                | Mauritania                | Northern Africa |
| Kingdom of Morocco                            | Morocco                   | Northern Africa |
| Sahrawi Arab Democratic Republic              | Sahrawi Republic          | Northern Africa |
| Republic of Tunisia                           | Tunisia                   | Northern Africa |
| Republic of Angola                            |  Angola                   | Southern Africa |
|  Republic of Botswana                         |  Botswana                 | Southern Africa |
|  Kingdom of Eswatini                          |  Eswatini                 | Southern Africa |
|  Kingdom of Lesotho                           |  Lesotho                  | Southern Africa |
|  Republic of Malawi                           |  Malawi                   | Southern Africa |
|  Republic of Mozambique                       |  Mozambique               | Southern Africa |
|  Republic of Namibia                          |  Namibia                  | Southern Africa |
|  Republic of South Africa                     |  South Africa             | Southern Africa |
|  Republic of Zambia                           |  Zambia                   | Southern Africa |
|  Republic of Zimbabwe                         |  Zimbabwe                 | Southern Africa |
| Republic of Benin                             |  Benin                    | Western Africa  |
|  Burkina Faso                                 |  Burkina Faso             | Western Africa  |
|  Republic of Cabo Verde                       |  Cabo Verde               | Western Africa  |
|  Republic of Côte d’Ivoire                    |  Côte d’Ivoire            | Western Africa  |
|  Republic of the Gambia                       |  Gambia                   | Western Africa  |
|  Republic of Ghana                            |  Ghana                    | Western Africa  |
|  Republic of Guinea                           |  Guinea                   | Western Africa  |
|  Republic of Guinea-Bissau                    |  Guinea-Bissau            | Western Africa  |
|  Republic of Liberia                          |  Liberia                  | Western Africa  |
|  Republic of Mali                             |  Mali                     | Western Africa  |
|  Republic of Niger                            |  Niger                    | Western Africa  |
|  Federal Republic of Nigeria                  |  Nigeria                  | Western Africa  |
|  Republic of Senegal                          |  Senegal                  | Western Africa  |
|  Republic of Sierra Leone                     |  Sierra Leone             | Western Africa  |
|  Togolese Republic                            |  Togo                     | Western Africa  |
